# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: vriesdemichael.mm-mcp
PackageVersion: 0.1.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: mm-mcp.exe
  PortableCommandAlias: mm-mcp
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/vriesdemichael/mm-mcp/releases/download/v0.1.0/mm-mcp_0.1.0_windows_amd64.zip
  InstallerSha256: 7F5A9F29EAF6EF5FD230D6AF66389C0E4CA9304D6B5476D42722789DE5961A7E
- Architecture: arm64
  InstallerUrl: https://github.com/vriesdemichael/mm-mcp/releases/download/v0.1.0/mm-mcp_0.1.0_windows_arm64.zip
  InstallerSha256: E08EF5DE50018921C4D49E042F69B5ABECFBF874B4D68AFEEA21FCAF67049BF1
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-07
